### ISSUE TITLE
Append headers in the interceptor

### ISSUE THREAD

**Issue by makkart** [gund/ng2-http-interceptor#23]
First of all, good work so far!

Second, is there a way (or are you considering a way) to append headers to the request inside the interceptor. That is the main thing I would need an http-interceptor for and yours is the best one i have found so far. So you know, it would be nice =) 

Thanks.

**Comment by gund** [comment]
Thanks for your interest.

This lib was designed to have full control of requests/responses so yep you can add headers to requests.
The way to do it is straightforward, suppose you have next interceptor:

```ts
httpInterceptor.request().addInterceptor((data: any[], method: string) => {
  // data - Here is an array of arguments which where passed when made http request
  // so for http.get('/my-url') it will be simply ['/my-url']
  // You can modify it the way you want but keep in mind that this array will then be
  // a set of arguments provided to make an http request
  // And since you can add headers to every request in Angular2 Http service
  // you can do same here - just update `data` array like so:
  data[1] = new RequestOptions({headers: new Headers({'X-My-Header': 'value'})});
  // Index 1 here is because RequestOptions is the second argument for Http.get() method
  // and data[0] - is the request url which you also can verify/change
  return data;
});
```

This is "dirty" way to do it because you probably want to check if `RequestOptions` already passed to the request and then you will need to add only headers you want, but it gives you an idea how to do this in basic.
Also please note that for some requests like `post` index of RequestOptions is shifted right because it has body argument before.

Hope all that I wrote is easy to understand =)

And since this feature already supported I will close issue but feel free to continue discussion if you have more questions or whatever.

**Comment by makkart** [comment]
Thank you! I actually tried to append "new Headers()" to the data Array but with no luck. Didnt think of RequestOptions. Awesome, thanks!
